//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWCFTriggerService")]
interface IWCFTriggerService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCFTriggerService/Ping", ReplyAction = "http://tempuri.org/IWCFTriggerService/PingResponse")]
    void Ping();

    //[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCFTriggerService/Ping", ReplyAction = "http://tempuri.org/IWCFTriggerService/PingResponse")]
    //System.Threading.Tasks.Task PingAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
interface IWCFTriggerServiceChannel : IWCFTriggerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
partial class WCFTriggerServiceClient : System.ServiceModel.ClientBase<IWCFTriggerService>, IWCFTriggerService
{
    
    public WCFTriggerServiceClient()
    {
    }
    
    public WCFTriggerServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WCFTriggerServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFTriggerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFTriggerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }

    public void Ping()
    {
        base.Channel.Ping();
    }

    //public System.Threading.Tasks.Task PingAsync()
    //{
    //    return base.Channel.PingAsync();
    //}
}
